### ISSUE TITLE
Remove HelloWorld.java

### ISSUE THREAD

**Issue by raaaimund** [navyareddy001/student-management-application#2]
The file HelloWorld.java should be deleted.

https://github.com/navyareddy001/student-management-application/blob/38f80106d1c636c58844a84a63a7bb328d8db1b0/HelloWorld.java#L1

Edit all changes in the branch `assignment1` and commit + push those changes and add me as a reviewer.

**Comment by khandesaiprakash** [comment]
I am deleted the HelloWorld.java
