### ISSUE TITLE
Rename StudentManagementApplication to Main

### ISSUE THREAD

**Issue by raaaimund** [navyareddy001/student-management-application#3]
Rename the java file name and also class to `Main` instead of `StudentManagementApplication`.

https://github.com/navyareddy001/student-management-application/blob/38f80106d1c636c58844a84a63a7bb328d8db1b0/StudentManagementApplication.java#L1

Edit all changes in the branch `assignment1` and commit + push those changes and add me as a reviewer.

**Comment by navyareddy001** [comment]
Rename has been completed.
