### ISSUE TITLE
Remove blank lines

### ISSUE THREAD

**Issue by raaaimund** [navyareddy001/student-management-application#4]
Remove the blank lines in `StudentManagementApplication`.

https://github.com/navyareddy001/student-management-application/blob/38f80106d1c636c58844a84a63a7bb328d8db1b0/StudentManagementApplication.java#L9C1-L10C1

Edit all changes in the branch `assignment1` and commit + push those changes and add me as a reviewer.

**Comment by khandesaiprakash** [comment]
I removed the blank lines.
